export const SAVE_INSTANCE = "SAVE_INSTANCE";
export const REMOVE_INSTANCE = "REMOVE_INSTANCE";
export const UPDATE_INSTANCE = "UPDATE_INSTANCE";
export const SAVE_ALL_INSTANCES = "SAVE_ALL_INSTANCES";
export const DELETE_ALL_INSTANCES = "DELETE_ALL_INSTANCES";
export const INVALID_INSTANCE_CANNOT_SAVE = "INVALID_INSTANCE_CANNOT_SAVE";

export const SAVE_USER_ID = "SAVE_USER_ID";
export const SAVE_USER_DATA = "SAVE_USER_DATA";
export const SHOW_LOADER = "SHOW_LOADER";

export const HIDE_MODAL = 'HIDE_MODAL';
export const SHOW_MODAL = 'SHOW_MODAL';

export const HIDE_MESSAGE = 'HIDE_MESSAGE';
export const SHOW_MESSAGE = 'SHOW_MESSAGE';